### ISSUE TITLE
gradle build fail

### ISSUE THREAD

**Issue by zeyangli** [BBVA/mirrorgate-jenkins-builds-collector#1]
[root@node1 mirrorgate-jenkins-builds-collector-0.0.7]# gradle clean build -x test

FAILURE: Build failed with an exception.

* What went wrong:
No signature of method: org.jenkinsci.gradle.plugins.jpi.JpiPlugin$_configurePublishing_closure18.doCall() is applicable for argument types: () values: []
Possible solutions: isCase(java.lang.Object), isCase(java.lang.Object), findAll(), findAll(), findAll(groovy.lang.Closure), findAll(groovy.lang.Closure)

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

Deprecated Gradle features were used in this build, making it incompatible with Gradle 5.0.
Use '--warning-mode all' to show the individual deprecation warnings.
See https://docs.gradle.org/4.10/userguide/command_line_interface.html#sec:command_line_warnings

BUILD FAILED in 1s

centos7  gradle4.10

**Comment by alfonso-presa** [comment]
Please, try `./gradlew clean build -x test` to use the gradle wrapper provided (note de `w`after gradle).

**Comment by zeyangli** [comment]
[root@node1 mirrorgate-jenkins-builds-collector-0.0.7]# ./gradlew clean build -x test
Repository https://repo1.maven.org/maven2/ replaced by http://maven.aliyun.com/nexus/content/groups/public/.
Repository https://repo1.maven.org/maven2/ replaced by http://maven.aliyun.com/nexus/content/groups/public/.
:clean
:localizer
:compileJava
注: /root/test/mirrorgate-jenkins-builds-collector-0.0.7/src/main/java/jenkins/plugins/mirrorgate/MirrorGatePublisher.java使用或覆盖了已过时的 API。
注: 有关详细信息, 请使用 -Xlint:deprecation 重新编译。
注: /root/test/mirrorgate-jenkins-builds-collector-0.0.7/src/main/java/com/bbva/arq/devops/ae/mirrorgate/jenkins/plugin/builder/BuildBuilder.java使用了未经检查或不安全的操作。
注: 有关详细信息, 请使用 -Xlint:unchecked 重新编译。
:compileGroovy UP-TO-DATE
:processResources
:classes
:war
:signArchives SKIPPED
:assemble UP-TO-DATE
:check
:build

BUILD SUCCESSFUL

Total time: 17.375 secs

This build could be faster, please consider using the Gradle Daemon: https://docs.gradle.org/2.10/userguide/gradle_daemon.html
[root@node1 mirrorgate-jenkins-builds-collector-0.0.7]# ls
build            gradle             gradlew.bat  media
build.gradle     gradle.properties  Jenkinsfile  README.md
CONTRIBUTING.md  gradlew            LICENSE      src

**Comment by zeyangli** [comment]
have not "target" dir. Please help me try it again. Thank you!

**Comment by zeyangli** [comment]
plugin is in build/libs/

[root@node1 libs]# pwd
/root/test/mirrorgate-jenkins-builds-collector-0.0.7/build/libs
[root@node1 libs]# ls
mirrorgate-publisher.hpi

Thank you!  @alfonso-presa
