### ISSUE TITLE
No data to display！

### ISSUE THREAD

**Issue by zeyangli** [BBVA/mirrorgate-jenkins-builds-collector#3]
I have configured Jenkins, but found no data to display. The official documentation just says how to configure Jenkins, but there is no detailed explanation of how the data is displayed. Please help me to look at this issue.

**Comment by kdaimiel** [comment]
You need to create and configurate a Dashboard in MirrorGate to be able to see the builds. Please check [MirrorGate dashboard](https://github.com/BBVA/mirrorgate) documentation.

**Comment by zeyangli** [comment]
[https://github.com/BBVA/mirrorgate/blob/master/mirrorgate-docs/src/assets/img/backoffice.png](url)

Please take a look at this picture. Is the buildjobs field filled in with the project name on jenkins?

**Comment by zeyangli** [comment]
I wrote the project name of Jenkins, but I don't know why I waited for a long time and there is still no data on the page. I want to estimate the configuration file, but I don't know what went wrong.

**Comment by kdaimiel** [comment]
Have you tried to throw a build after Jenkins  Pluging was configurated? Please also check if buildls are saved in Data Base.

**Comment by zeyangli** [comment]
My goodness, I am so stupid, haha. It turned out to be the case. I saw that when I triggered the project build, the log had an output mirrorgate. Thank you very much, I will test the jira plugin in the next step. If you have any questions, please advise me!

**Comment by kdaimiel** [comment]
Nice!
